import Navbar from './_components/navbar';
import Sidebar from './_components/sidebar';

export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className='flex min-h-screen w-full flex-col bg-muted/50'>
			<Sidebar />
			<div className='flex flex-col sm:gap-4 sm:py-4 sm:pl-14'>
				<Navbar />
				{children}
			</div>
		</div>
	);
}
